### ISSUE TITLE
Option "is_first_big" not work always

### ISSUE THREAD

**Issue by beliyadm** [absentik/jMosaic#3]
Hi, thanks for the plugin, but some bugs.
My settings
    $('.content_image').jMosaic({
		items_type: "img",
		min_row_height: 110,
		margin: 3,
		is_first_big: true
	});
Some blocks .content_image work fine, some not, Screen http://easycaptures.com/fs/uploaded/838/0766036433.jpg
Use last version 0.1.3

**Comment by absentik** [comment]
Hi. Option `is_first_big` indicates the position of row with largest images at the start or end. 
However, such its height may be different from all the other lines slightly - this is normal. Its size depends on the results of fitting elements.

**Comment by beliyadm** [comment]
Hi,  thank you for your answer, understood the reason.
